- name: Install docker
  hosts: my_vms
  gather_facts: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      become: yes

    - name: Install required packages
      package:
        name:
          - ca-certificates
          - curl
        state: present
      become: yes
    
    - name: Ensure Keyrings directory exists
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: download gpg key to keyrings directory
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        keyring: /etc/apt/keyrings/docker.asc
      become: true 
    
    - name: Add APT Repository
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu  
        {{ ansible_distribution_release }} stable"
        state: present
      become: true

    - name: Update apt cache
      apt:
        update_cache: yes
      become: yes

    - name: Install necessary docker packages
      apt:
        name: "{{ item }}"
        state: latest
      with_items: 
        - docker-ce 
        - docker-ce-cli 
        - containerd.io 
        - docker-buildx-plugin 
        - docker-compose-plugin
      become: true
      
    - name: Make sure a Docker is running
      systemd_service:
        state: started
        name: docker

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /opt/fastapi
        state: directory
        mode: '0755'

    - name: Copy docker compose file to VM
      ansible.builtin.copy:
        src: /home/vboxuser/Desktop/fastapi-sample-project/docker-compose.yml
        dest: /opt/fastapi/dokcer-compose.yml
        # owner: foo
        # group: foo
        # mode: '0644'


    - name: Run docker image
      community.docker.docker_compose_v2:
        build: always
        project_src: /opt/fastapi/
    

    
    
