- name: Install docker
  hosts: localhost
  gather_facts: yes
  connection: local
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      become: yes

    - name: Install required packages
      package:
        name:
          - ca-certificates
          - curl
        state: present
      become: yes
    
    - name: Ensure Keyrings directory exists
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: download gpg key to keyrings directory
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        keyring: /etc/apt/keyrings/docker.asc
      become: true 
    
    - name: Add APT Repository
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu  
        {{ ansible_distribution_release }} stable"
        state: present
      become: true

    - name: Update apt cache
      apt:
        update_cache: yes
      become: yes

    - name: Install necessary docker packages
      apt:
        name: "{{ item }}"
        state: latest
      with_items: 
        - docker-ce 
        - docker-ce-cli 
        - containerd.io 
        - docker-buildx-plugin 
        - docker-compose-plugin
      become: true
      
    - name: Make sure a Docker is running
      systemd_service:
        state: started
        name: docker

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker 
        append: true
      become: true
