name: Deployment

on:
    push:
        tags:
            - 'v**'

jobs:
    build_and_push_docker:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Log into docker hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD}}

            # - name: Setup QEMU
            #   uses: docker/setup-qemu-action@v3

            # - name: Set up Docker Buildx
            #   uses: docker/setup-buildx-action@v3

            - name: Build Docker Image
              run: |
                IMAGE_TAG=${GITHUB_REF##*/}
                docker build -t al0314/fastapi-sample-project-CI:$IMAGE_TAG .
    
            - name: Push Docker Image to Docker Hub
              run: |
                docker push al0314/fastapi-sample-project-CI:$IMAGE_TAG
                
