name: Enable auto merge

on:

  workflow_dispatch:
  workflow_run:
        
        workflows: ["Code testing"]
        types:
            - completed
jobs:
    create-pull-request: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Create Pull Request
              id: cpr
              uses: peter-evans/create-pull-request@v3
              with:
                token: ${{ secrets.GIT_PAT2 }}
      
            - name: Enable Pull Request Automerge
              if: steps.cpr.outputs.pull-request-operation == 'created'
              uses: peter-evans/enable-pull-request-automerge@v3
              with:
                token: ${{ secrets.GIT_PAT2 }}
                pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
                merge-method: rebase
